### ISSUE TITLE
The ThermOS don't change the GPIO status.

### ISSUE THREAD

**Issue by adrianobrum** [mholgatem/ThermOS#2]
When I'm in the settings and I try to save the GPIO number BCM or BOARD the website give me a 500 error because of overload. After I refresh the page I can see that GPIO it's saved but when I try to work, that don't work, it's always off. Example:

My GPIO Heater is 17.

17 it's saved but never change their status.
After change the GPIO to 22 the GPIO 17 turn ON and I cannot control them.

Why are this happening?

My Rasoberry is B version. I have a Raspberry Pi 2 too.

**Comment by mholgatem** [comment]
it looks like there is an error in the way that switching from board to bcm is being handled (it's extra tricky because it has to be synced between the web app and a daemon). I'll get around to fixing it soon, but in the meantime i recommend just sticking with BOARD numbering. 

GPIO 17 = board 11
GPIO 22 = board 15

I'm not quite sure what you are getting at with the rest of this though. 

> My GPIO Heater is 17.
17 it's saved but never change their status.
After change the GPIO to 22 the GPIO 17 turn ON and I cannot control them.

click on the 'Logs' button to make sure that the daemon is running if nothing is changing.
or type this in your console:
`sudo systemctl status thermostat-daemon`
it should say 'running': otherwise type
`sudo systemctl start thermostat-daemon`
to restart it

**Comment by adrianobrum** [comment]
I get this in 'Logs':

`pi@raspberrypi:~ $ sudo systemctl status thermostat-daemon
● thermostat-daemon.service - ThermOS-daemon
   Loaded: loaded (/lib/systemd/system/thermostat-daemon.service; enabled)
   Active: active (running) since Tue 2016-10-18 19:48:16 UTC; 1h 54min ago
  Process: 1612 ExecReload=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
 Main PID: 660 (python)
   CGroup: /system.slice/thermostat-daemon.service
           └─660 /usr/bin/python -u thermostat_daemon.py

Oct 18 21:42:12 raspberrypi python[660]: heatStatus = 1
Oct 18 21:42:12 raspberrypi python[660]: coolStatus = 0
Oct 18 21:42:12 raspberrypi python[660]: fanStatus = 1
Oct 18 21:42:17 raspberrypi python[660]: DEBUG: STATE: Switching to heat
Oct 18 21:42:17 raspberrypi python[660]: DEBUG: hvacState = HEAT
Oct 18 21:42:17 raspberrypi python[660]: indoorTemp = 17.25
Oct 18 21:42:17 raspberrypi python[660]: targetTemp = 20.5
Oct 18 21:42:17 raspberrypi python[660]: heatStatus = 1
Oct 18 21:42:17 raspberrypi python[660]: coolStatus = 0
Oct 18 21:42:17 raspberrypi python[660]: fanStatus = 1
`

My heater it's not turning on, I'm using BOARD 15/ GPIO 22 and nothing. Why it's this happening?

**Comment by mholgatem** [comment]
According to what you posted, both the heat and fan gpio are turned on ( which is correct ). So there must be a hardware misconfiguration. You have the pins hooked up to a relay I assume? Are you providing power for both the logic circuit (5v) and the ac unit itself (12v-24v)?

**Comment by adrianobrum** [comment]
Now it's a hardware problem, Thanks for your time.
