### ISSUE TITLE
Schedule doesn't allow for decimal point temperature.

### ISSUE THREAD

**Issue by 10481** [mholgatem/ThermOS#4]
I left this project for a little while, and jumped back onto it and it's working great. Something I've noticed, though, is that when I go to set a schedule, I can't set a value for something like 21.5. I can set decimal values in the manual control zone, but not in the schedule.

**Comment by mholgatem** [comment]
ah, yes. I'm not quite sure why I set them to **int** instead of **float**, probably just an oversight. You can fix the issue by editing lines [364 and 366 in thermostat_web.py](https://github.com/mholgatem/ThermOS/blob/master/thermostat_web.py#L364-L366). On each line, change the **int()** to **float()** and you should be good

**Comment by 10481** [comment]
Worked perfect. Thanks!

**Comment by mholgatem** [comment]
of course. I love when people report problems. I'll make the fix in the main repo in a bit. I just realized that I don't have a way to schedule just the fan, so when I make those changes, I'll fix this as well.
